import type { Language } from "../domain/markets";

const copy = {
  ja: {
    navCollection: "コレクション",
    navHeritage: "華山と有田",
    navCondition: "状態基準",
    navChefs: "料理人の方へ",
    navSelection: "選品リスト",
    demoNotice: "デモサイト：画像・価格・在庫・送料は参考データです。",
    partner: "華山 正規海外販売パートナー",
    explore: "コレクションを見る",
    forChefs: "料理人の方へ",
    addSelection: "選品リストに追加",
    viewVessel: "器を見る",
    conditionReport: "コンディションレポート",
    noImpact: "機能への影響なし",
    demoPrice: "デモ参考価格",
    sampleStock: "参考在庫",
    pieces: "点",
    sourceNote: "参考画像。正式公開前に華山承認素材へ差し替えます。",
    language: "言語",
    market: "市場",
    theme: "テーマを切り替える",
    menu: "メニュー",
    emptySelection: "選品リストはまだ空です。",
    browseCollection: "器を選ぶ",
    subtotal: "器の小計",
    shipping: "参考国際送料",
    total: "参考合計",
    submitInquiry: "購入相談を送る",
    remove: "削除",
    quantity: "数量"
  },
  en: {
    navCollection: "Collection",
    navHeritage: "Kazan & Arita",
    navCondition: "Condition Standard",
    navChefs: "For Chefs",
    navSelection: "Selection",
    demoNotice: "Demo site: images, prices, stock, and shipping are reference data.",
    partner: "Authorized Overseas Sales Partner of Kazan",
    explore: "Explore the Collection",
    forChefs: "For Culinary Professionals",
    addSelection: "Add to Selection",
    viewVessel: "View Vessel",
    conditionReport: "Condition Report",
    noImpact: "No functional impact",
    demoPrice: "Demo reference price",
    sampleStock: "Sample availability",
    pieces: "pieces",
    sourceNote: "Reference image. Replace with owner-approved Kazan photography before public release.",
    language: "Language",
    market: "Market",
    theme: "Switch theme",
    menu: "Menu",
    emptySelection: "Your selection is currently empty.",
    browseCollection: "Browse vessels",
    subtotal: "Vessel subtotal",
    shipping: "Estimated international shipping",
    total: "Reference total",
    submitInquiry: "Submit an Inquiry",
    remove: "Remove",
    quantity: "Quantity"
  },
  "zh-TW": {
    navCollection: "器物精選",
    navHeritage: "華山與有田",
    navCondition: "狀態標準",
    navChefs: "主廚採購",
    navSelection: "選品清單",
    demoNotice: "Demo 網站：圖片、價格、庫存與運費皆為參考資料。",
    partner: "華山授權海外銷售夥伴",
    explore: "瀏覽器物",
    forChefs: "專業餐飲採購",
    addSelection: "加入選品清單",
    viewVessel: "查看器物",
    conditionReport: "Condition Report",
    noImpact: "不影響正常使用",
    demoPrice: "Demo 參考價格",
    sampleStock: "參考庫存",
    pieces: "件",
    sourceNote: "參考圖片。正式公開前將替換為華山核准攝影素材。",
    language: "語言",
    market: "市場",
    theme: "切換主題",
    menu: "選單",
    emptySelection: "選品清單目前是空的。",
    browseCollection: "選擇器物",
    subtotal: "器物小計",
    shipping: "國際運費預估",
    total: "參考總額",
    submitInquiry: "提交採購詢價",
    remove: "移除",
    quantity: "數量"
  }
} as const;

export function getCopy(language: Language) {
  return copy[language];
}
